Traceback (most recent call last):
  File "/home/s2113174/Projects-1/Elliptic/experiments/elliptic_experiment.py", line 237, in <module>
    main(args.verbose, args.N, args.train, args.deepgala, args.noise_level, args.proposal, args.fem_mcmc,
  File "/home/s2113174/Projects-1/Elliptic/experiments/elliptic_experiment.py", line 213, in main
    run_experiment(config_experiment,device)
  File "/home/s2113174/Projects-1/Elliptic/experiments/elliptic_experiment.py", line 129, in run_experiment
    pinn_nvs = train_elliptic(config_experiment, device=device)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2113174/Projects-1/Elliptic/elliptic_files/train_elliptic.py", line 151, in train_elliptic
    total_loss,losses = dg_elliptic.total_loss(data_int, left_bc, right_bc, loss_fn)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2113174/Projects-1/Base/dg.py", line 49, in total_loss
    losses = self.losses(*args,**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2113174/Projects-1/Elliptic/elliptic_files/elliptic.py", line 65, in losses
    loss_pde = self.pde_loss(data_interior,loss_fn)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2113174/Projects-1/Elliptic/elliptic_files/elliptic.py", line 48, in pde_loss
    elliptic_pred = self.elliptic_pde(data_interior)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2113174/Projects-1/Base/dg.py", line 36, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2113174/Projects-1/Elliptic/elliptic_files/elliptic.py", line 35, in elliptic_pde
    u = self.model(data_domain)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2113174/anaconda3/envs/fenicsx-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2113174/anaconda3/envs/fenicsx-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2113174/Projects-1/Base/deep_models.py", line 267, in forward
    x = self.fourier_layer(x)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2113174/anaconda3/envs/fenicsx-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2113174/anaconda3/envs/fenicsx-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s2113174/Projects-1/Base/deep_models.py", line 96, in forward
    transformed = torch.matmul(xi, self.kernel)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (150x1 and 6x40)
